"""GA4 dimension and metric definitions.

Usage:
  - Comment out unnecessary items with cmd+/.
  - Add missing items using their GA4 API names.
  - The multiselect uses ``accept_new_options=True``, so values not listed
    here can still be entered manually in the UI.

Excluded categories (can still be entered manually if needed):
  - CM360 family (cm360*)
  - DV360 family (dv360*)
  - SA360 family (sa360*)
  - Cohort family (cohort*)
  - Publisher/Ad family (adFormat, adSourceName, adUnitName, publisherAd*)
  - Game-related (achievementId, character, level, groupId, virtualCurrencyName)
  - Crash-related (crashAffectedUsers, crashFreeUsersRate)
"""

# fmt: off

ALL_DIMENSIONS = [
    # Time -------------------------------------------------
    "date",
    "dateHour",
    # "dateHourMinute",
    "hour",
    "dayOfWeek",
    # "dayOfWeekName",
    "week",
    "month",
    "year",
    # "day",
    # "minute",
    # "nthDay",
    # "nthHour",
    # "nthMinute",
    # "nthMonth",
    # "nthWeek",
    # "nthYear",
    # "isoWeek",
    # "isoYear",
    # "isoYearIsoWeek",
    # "yearMonth",
    # "yearWeek",

    # Traffic source (session) -----------------------------
    "sessionDefaultChannelGroup",
    "sessionSource",
    "sessionMedium",
    "sessionSourceMedium",
    "sessionSourcePlatform",
    "sessionCampaignName",
    # "sessionCampaignId",
    # "sessionPrimaryChannelGroup",
    # "sessionManualAdContent",
    # "sessionManualCampaignId",
    # "sessionManualCampaignName",
    # "sessionManualCreativeFormat",
    # "sessionManualMarketingTactic",
    # "sessionManualMedium",
    # "sessionManualSource",
    # "sessionManualSourceMedium",
    # "sessionManualSourcePlatform",
    # "sessionManualTerm",
    # "sessionGoogleAdsAccountName",
    # "sessionGoogleAdsAdGroupId",
    # "sessionGoogleAdsAdGroupName",
    # "sessionGoogleAdsAdNetworkType",
    # "sessionGoogleAdsCampaignId",
    # "sessionGoogleAdsCampaignName",
    # "sessionGoogleAdsCampaignType",
    # "sessionGoogleAdsCreativeId",
    # "sessionGoogleAdsCustomerId",
    # "sessionGoogleAdsKeyword",
    # "sessionGoogleAdsQuery",

    # Traffic source (first user) --------------------------
    "firstUserSource",
    "firstUserMedium",
    "firstUserSourceMedium",
    "firstUserDefaultChannelGroup",
    "firstUserCampaignName",
    # "firstUserCampaignId",
    # "firstUserSourcePlatform",
    # "firstUserPrimaryChannelGroup",
    # "firstUserManualAdContent",
    # "firstUserManualCampaignId",
    # "firstUserManualCampaignName",
    # "firstUserManualCreativeFormat",
    # "firstUserManualMarketingTactic",
    # "firstUserManualMedium",
    # "firstUserManualSource",
    # "firstUserManualSourceMedium",
    # "firstUserManualSourcePlatform",
    # "firstUserManualTerm",
    # "firstUserGoogleAdsAccountName",
    # "firstUserGoogleAdsAdGroupId",
    # "firstUserGoogleAdsAdGroupName",
    # "firstUserGoogleAdsAdNetworkType",
    # "firstUserGoogleAdsCampaignId",
    # "firstUserGoogleAdsCampaignName",
    # "firstUserGoogleAdsCampaignType",
    # "firstUserGoogleAdsCreativeId",
    # "firstUserGoogleAdsCustomerId",
    # "firstUserGoogleAdsKeyword",
    # "firstUserGoogleAdsQuery",

    # Traffic source (key-event attribution) ---------------
    # "defaultChannelGroup",
    # "source",
    # "medium",
    # "sourceMedium",
    # "sourcePlatform",
    # "primaryChannelGroup",
    # "campaignId",
    # "campaignName",
    # "manualAdContent",
    # "manualCampaignId",
    # "manualCampaignName",
    # "manualCreativeFormat",
    # "manualMarketingTactic",
    # "manualMedium",
    # "manualSource",
    # "manualSourceMedium",
    # "manualSourcePlatform",
    # "manualTerm",
    # "googleAdsAccountName",
    # "googleAdsAdGroupId",
    # "googleAdsAdGroupName",
    # "googleAdsAdNetworkType",
    # "googleAdsCampaignId",
    # "googleAdsCampaignName",
    # "googleAdsCampaignType",
    # "googleAdsCreativeId",
    # "googleAdsCustomerId",
    # "googleAdsKeyword",
    # "googleAdsQuery",

    # Page / Content ---------------------------------------
    "pagePath",
    "pageTitle",
    "landingPage",
    "landingPagePlusQueryString",
    "pagePathPlusQueryString",
    "hostName",
    "contentGroup",
    # "contentId",
    # "contentType",
    # "fullPageUrl",
    # "pageLocation",
    # "pageReferrer",
    # "unifiedPagePathScreen",
    # "unifiedPageScreen",
    # "unifiedScreenClass",
    # "unifiedScreenName",

    # User / Demographics ----------------------------------
    "newVsReturning",
    "userAgeBracket",
    "userGender",
    # "brandingInterest",
    # "audienceId",
    # "audienceName",
    # "audienceResourceName",
    # "firstSessionDate",
    # "signedInWithUserId",

    # Device / Platform ------------------------------------
    "deviceCategory",
    "operatingSystem",
    "browser",
    # "operatingSystemVersion",
    # "operatingSystemWithVersion",
    # "deviceModel",
    # "mobileDeviceBranding",
    # "mobileDeviceMarketingName",
    # "mobileDeviceModel",
    # "screenResolution",
    # "platform",
    # "platformDeviceCategory",
    # "language",
    # "languageCode",
    # "appVersion",
    # "streamId",
    # "streamName",

    # Geography ---------------------------------------------
    "country",
    "region",
    "city",
    "language",
    # "countryId",
    # "cityId",
    # "continent",
    # "continentId",

    # Event / Conversion -----------------------------------
    "eventName",
    "isKeyEvent",
    # "searchTerm",
    # "fileExtension",
    # "fileName",
    # "linkClasses",
    # "linkDomain",
    # "linkId",
    # "linkText",
    # "linkUrl",
    # "outbound",
    # "percentScrolled",
    # "videoProvider",
    # "videoTitle",
    # "videoUrl",
    # "visible",
    # "method",

    # Ecommerce ---------------------------------------------
    # "currencyCode",
    # "itemAffiliation",
    # "itemBrand",
    # "itemCategory",
    # "itemCategory2",
    # "itemCategory3",
    # "itemCategory4",
    # "itemCategory5",
    # "itemId",
    # "itemListId",
    # "itemListName",
    # "itemListPosition",
    # "itemLocationID",
    # "itemName",
    # "itemPromotionCreativeName",
    # "itemPromotionCreativeSlot",
    # "itemPromotionId",
    # "itemPromotionName",
    # "itemVariant",
    # "orderCoupon",
    # "shippingTier",
    # "transactionId",

    # Other ------------------------------------------------
    # "comparison",
    # "testDataFilterId",
    # "testDataFilterName",
]

ALL_METRICS = [
    # Session -----------------------------------------------
    "sessions",
    "engagedSessions",
    "engagementRate",
    "bounceRate",
    "averageSessionDuration",
    "sessionsPerUser",
    # "sessionKeyEventRate",

    # User --------------------------------------------------
    "activeUsers",
    "newUsers",
    "totalUsers",
    # "active1DayUsers",
    # "active7DayUsers",
    # "active28DayUsers",
    # "dauPerMau",
    # "dauPerWau",
    # "wauPerMau",

    # Pageview ----------------------------------------------
    "screenPageViews",
    "screenPageViewsPerSession",
    # "screenPageViewsPerUser",

    # Engagement --------------------------------------------
    "userEngagementDuration",
    "eventCount",
    "eventsPerSession",
    # "eventCountPerUser",
    # "eventValue",
    # "scrolledUsers",

    # Conversion --------------------------------------------
    "keyEvents",
    "conversions",
    # "userKeyEventRate",

    # Ecommerce (purchase) ----------------------------------
    "ecommercePurchases",
    "purchaseRevenue",
    "addToCarts",
    "checkouts",
    "transactions",
    # "totalRevenue",
    # "grossPurchaseRevenue",
    # "averagePurchaseRevenue",
    # "averagePurchaseRevenuePerPayingUser",
    # "averagePurchaseRevenuePerUser",
    # "averageRevenuePerUser",
    # "totalPurchasers",
    # "purchaserRate",
    # "firstTimePurchasers",
    # "firstTimePurchaserRate",
    # "firstTimePurchasersPerNewUser",
    # "transactionsPerPurchaser",
    # "purchaseToViewRate",

    # Ecommerce (item) --------------------------------------
    # "itemRevenue",
    # "grossItemRevenue",
    # "itemRefundAmount",
    # "itemDiscountAmount",
    # "itemsPurchased",
    # "itemsAddedToCart",
    # "itemsCheckedOut",
    # "itemsViewed",
    # "itemsViewedInList",
    # "itemsViewedInPromotion",
    # "itemsClickedInList",
    # "itemsClickedInPromotion",
    # "itemListClickEvents",
    # "itemListViewEvents",
    # "itemListClickThroughRate",
    # "itemViewEvents",
    # "itemPromotionClickThroughRate",
    # "promotionClicks",
    # "promotionViews",
    # "cartToViewRate",
    # "refundAmount",
    # "shippingAmount",
    # "taxAmount",

    # Ads ---------------------------------------------------
    # "advertiserAdClicks",
    # "advertiserAdCost",
    # "advertiserAdCostPerClick",
    # "advertiserAdCostPerKeyEvent",
    # "advertiserAdImpressions",
    # "returnOnAdSpend",
    # "totalAdRevenue",

    # Search Console integration ----------------------------
    # "organicGoogleSearchClicks",
    # "organicGoogleSearchImpressions",
    # "organicGoogleSearchClickThroughRate",
    # "organicGoogleSearchAveragePosition",
]

# fmt: on
