"""GA4 ディメンション・メトリクス定義

使い方:
  - 不要な項目は cmd+/ でコメントアウト
  - 追加したい項目はGA4 API名をそのまま追記
  - multiselect には accept_new_options=True があるので
    ここに無い項目もUI上で手入力可能

除外済みカテゴリ（必要なら手入力で追加可能）:
  - CM360系 (cm360*)
  - DV360系 (dv360*)
  - SA360系 (sa360*)
  - Cohort系 (cohort*)
  - Publisher/Ad系 (adFormat, adSourceName, adUnitName, publisherAd*)
  - ゲーム系 (achievementId, character, level, groupId, virtualCurrencyName)
  - Crash系 (crashAffectedUsers, crashFreeUsersRate)
"""

# fmt: off

ALL_DIMENSIONS = [
    # 時間 -------------------------------------------------
    "date",
    "dateHour",
    # "dateHourMinute",
    "hour",
    "dayOfWeek",
    # "dayOfWeekName",
    "week",
    "month",
    "year",
    # "day",
    # "minute",
    # "nthDay",
    # "nthHour",
    # "nthMinute",
    # "nthMonth",
    # "nthWeek",
    # "nthYear",
    # "isoWeek",
    # "isoYear",
    # "isoYearIsoWeek",
    # "yearMonth",
    # "yearWeek",

    # トラフィックソース（セッション） ----------------------
    "sessionDefaultChannelGroup",
    "sessionSource",
    "sessionMedium",
    "sessionSourceMedium",
    "sessionSourcePlatform",
    "sessionCampaignName",
    # "sessionCampaignId",
    # "sessionPrimaryChannelGroup",
    # "sessionManualAdContent",
    # "sessionManualCampaignId",
    # "sessionManualCampaignName",
    # "sessionManualCreativeFormat",
    # "sessionManualMarketingTactic",
    # "sessionManualMedium",
    # "sessionManualSource",
    # "sessionManualSourceMedium",
    # "sessionManualSourcePlatform",
    # "sessionManualTerm",
    # "sessionGoogleAdsAccountName",
    # "sessionGoogleAdsAdGroupId",
    # "sessionGoogleAdsAdGroupName",
    # "sessionGoogleAdsAdNetworkType",
    # "sessionGoogleAdsCampaignId",
    # "sessionGoogleAdsCampaignName",
    # "sessionGoogleAdsCampaignType",
    # "sessionGoogleAdsCreativeId",
    # "sessionGoogleAdsCustomerId",
    # "sessionGoogleAdsKeyword",
    # "sessionGoogleAdsQuery",

    # トラフィックソース（初回ユーザー） --------------------
    "firstUserSource",
    "firstUserMedium",
    "firstUserSourceMedium",
    "firstUserDefaultChannelGroup",
    "firstUserCampaignName",
    # "firstUserCampaignId",
    # "firstUserSourcePlatform",
    # "firstUserPrimaryChannelGroup",
    # "firstUserManualAdContent",
    # "firstUserManualCampaignId",
    # "firstUserManualCampaignName",
    # "firstUserManualCreativeFormat",
    # "firstUserManualMarketingTactic",
    # "firstUserManualMedium",
    # "firstUserManualSource",
    # "firstUserManualSourceMedium",
    # "firstUserManualSourcePlatform",
    # "firstUserManualTerm",
    # "firstUserGoogleAdsAccountName",
    # "firstUserGoogleAdsAdGroupId",
    # "firstUserGoogleAdsAdGroupName",
    # "firstUserGoogleAdsAdNetworkType",
    # "firstUserGoogleAdsCampaignId",
    # "firstUserGoogleAdsCampaignName",
    # "firstUserGoogleAdsCampaignType",
    # "firstUserGoogleAdsCreativeId",
    # "firstUserGoogleAdsCustomerId",
    # "firstUserGoogleAdsKeyword",
    # "firstUserGoogleAdsQuery",

    # トラフィックソース（キーイベント帰属） ----------------
    # "defaultChannelGroup",
    # "source",
    # "medium",
    # "sourceMedium",
    # "sourcePlatform",
    # "primaryChannelGroup",
    # "campaignId",
    # "campaignName",
    # "manualAdContent",
    # "manualCampaignId",
    # "manualCampaignName",
    # "manualCreativeFormat",
    # "manualMarketingTactic",
    # "manualMedium",
    # "manualSource",
    # "manualSourceMedium",
    # "manualSourcePlatform",
    # "manualTerm",
    # "googleAdsAccountName",
    # "googleAdsAdGroupId",
    # "googleAdsAdGroupName",
    # "googleAdsAdNetworkType",
    # "googleAdsCampaignId",
    # "googleAdsCampaignName",
    # "googleAdsCampaignType",
    # "googleAdsCreativeId",
    # "googleAdsCustomerId",
    # "googleAdsKeyword",
    # "googleAdsQuery",

    # ページ / コンテンツ -----------------------------------
    "pagePath",
    "pageTitle",
    "landingPage",
    "landingPagePlusQueryString",
    "pagePathPlusQueryString",
    "hostName",
    "contentGroup",
    # "contentId",
    # "contentType",
    # "fullPageUrl",
    # "pageLocation",
    # "pageReferrer",
    # "unifiedPagePathScreen",
    # "unifiedPageScreen",
    # "unifiedScreenClass",
    # "unifiedScreenName",

    # ユーザー / デモグラ -----------------------------------
    "newVsReturning",
    "userAgeBracket",
    "userGender",
    # "brandingInterest",
    # "audienceId",
    # "audienceName",
    # "audienceResourceName",
    # "firstSessionDate",
    # "signedInWithUserId",

    # デバイス / プラットフォーム ----------------------------
    "deviceCategory",
    "operatingSystem",
    "browser",
    # "operatingSystemVersion",
    # "operatingSystemWithVersion",
    # "deviceModel",
    # "mobileDeviceBranding",
    # "mobileDeviceMarketingName",
    # "mobileDeviceModel",
    # "screenResolution",
    # "platform",
    # "platformDeviceCategory",
    # "language",
    # "languageCode",
    # "appVersion",
    # "streamId",
    # "streamName",

    # 地域 --------------------------------------------------
    "country",
    "region",
    "city",
    "language",
    # "countryId",
    # "cityId",
    # "continent",
    # "continentId",

    # イベント / コンバージョン -----------------------------
    "eventName",
    "isKeyEvent",
    # "searchTerm",
    # "fileExtension",
    # "fileName",
    # "linkClasses",
    # "linkDomain",
    # "linkId",
    # "linkText",
    # "linkUrl",
    # "outbound",
    # "percentScrolled",
    # "videoProvider",
    # "videoTitle",
    # "videoUrl",
    # "visible",
    # "method",

    # eコマース ---------------------------------------------
    # "currencyCode",
    # "itemAffiliation",
    # "itemBrand",
    # "itemCategory",
    # "itemCategory2",
    # "itemCategory3",
    # "itemCategory4",
    # "itemCategory5",
    # "itemId",
    # "itemListId",
    # "itemListName",
    # "itemListPosition",
    # "itemLocationID",
    # "itemName",
    # "itemPromotionCreativeName",
    # "itemPromotionCreativeSlot",
    # "itemPromotionId",
    # "itemPromotionName",
    # "itemVariant",
    # "orderCoupon",
    # "shippingTier",
    # "transactionId",

    # その他 ------------------------------------------------
    # "comparison",
    # "testDataFilterId",
    # "testDataFilterName",
]

ALL_METRICS = [
    # セッション --------------------------------------------
    "sessions",
    "engagedSessions",
    "engagementRate",
    "bounceRate",
    "averageSessionDuration",
    "sessionsPerUser",
    # "sessionKeyEventRate",

    # ユーザー ----------------------------------------------
    "activeUsers",
    "newUsers",
    "totalUsers",
    # "active1DayUsers",
    # "active7DayUsers",
    # "active28DayUsers",
    # "dauPerMau",
    # "dauPerWau",
    # "wauPerMau",

    # ページビュー ------------------------------------------
    "screenPageViews",
    "screenPageViewsPerSession",
    # "screenPageViewsPerUser",

    # エンゲージメント --------------------------------------
    "userEngagementDuration",
    "eventCount",
    "eventsPerSession",
    # "eventCountPerUser",
    # "eventValue",
    # "scrolledUsers",

    # コンバージョン ----------------------------------------
    "keyEvents",
    "conversions",
    # "userKeyEventRate",

    # eコマース（購入） -------------------------------------
    "ecommercePurchases",
    "purchaseRevenue",
    "addToCarts",
    "checkouts",
    "transactions",
    # "totalRevenue",
    # "grossPurchaseRevenue",
    # "averagePurchaseRevenue",
    # "averagePurchaseRevenuePerPayingUser",
    # "averagePurchaseRevenuePerUser",
    # "averageRevenuePerUser",
    # "totalPurchasers",
    # "purchaserRate",
    # "firstTimePurchasers",
    # "firstTimePurchaserRate",
    # "firstTimePurchasersPerNewUser",
    # "transactionsPerPurchaser",
    # "purchaseToViewRate",

    # eコマース（アイテム） ---------------------------------
    # "itemRevenue",
    # "grossItemRevenue",
    # "itemRefundAmount",
    # "itemDiscountAmount",
    # "itemsPurchased",
    # "itemsAddedToCart",
    # "itemsCheckedOut",
    # "itemsViewed",
    # "itemsViewedInList",
    # "itemsViewedInPromotion",
    # "itemsClickedInList",
    # "itemsClickedInPromotion",
    # "itemListClickEvents",
    # "itemListViewEvents",
    # "itemListClickThroughRate",
    # "itemViewEvents",
    # "itemPromotionClickThroughRate",
    # "promotionClicks",
    # "promotionViews",
    # "cartToViewRate",
    # "refundAmount",
    # "shippingAmount",
    # "taxAmount",

    # 広告 --------------------------------------------------
    # "advertiserAdClicks",
    # "advertiserAdCost",
    # "advertiserAdCostPerClick",
    # "advertiserAdCostPerKeyEvent",
    # "advertiserAdImpressions",
    # "returnOnAdSpend",
    # "totalAdRevenue",

    # Search Console連携 ------------------------------------
    # "organicGoogleSearchClicks",
    # "organicGoogleSearchImpressions",
    # "organicGoogleSearchClickThroughRate",
    # "organicGoogleSearchAveragePosition",
]

# fmt: on
